local _, addon = ...

local expansion = KrowiAF.NewBuildVersion("TheWarWithin", 11)
local minor = expansion:Minor(0)
minor:Patch(0, addon.L["The War Within (pre-patch)"])
minor:Patch(2, addon.L["The War Within"])
minor:Patch(5, addon.L["WoW's 20th Anniversary"])
minor:Patch(7, addon.L["Siren Isle"])
minor = expansion:Minor(1)
minor:Patch(0, addon.L["Undermine(d)"])
minor:Patch(5, addon.L["Nightfall"])
minor:Patch(7, addon.L["Legacy of Arathor"])
minor = expansion:Minor(2)
minor:Patch(0, addon.L["Ghosts of K'aresh"])
minor:Patch(5, addon.L["Legion Remix"])
minor:Patch(7, addon.L["The Warning"])