-- [[ Exported at 2022-06-04 19-09-36 ]] --
-- [[ This code is automatically generated as an export from ]] --
-- [[ an SQLite database and is not meant for manual edit. ]] --

-- [[ German translation by Ta, 2022-05-31 ]] --

-- [[ Namespaces ]] --
local addonName, addon = ...;
local L = LibStub(addon.Libs.AceLocale):NewLocale(addonName, "deDE");
if not L then return end

local tab = "|T:1:8|t";
L["TAB"] = tab;

-- Load strings into the localization that are already localized by Blizzard
addon.GlobalStrings.Load(L);
addon.Plugins:LoadLocalization(L);

L["Achievement points earned by"] = "Erfolgspunkte erzielt durch";
L["Achievements"] = "Erfolge";
L["Expansions"] = "Addons";
L["Events"] = "Events";
L["PvP"] = "PvP";
L["Specials"] = "Spezial";
L["Merge Small Categories"] = "Kleine Kategorien zusammenführen";
L["Obtainable"] = "Verfügbar";
L["Not Obtainable"] = "Nicht Verfügbar";
L["Select all"] = "Alle auswählen";
L["Covenant"] = "Pakt";
L["Collapse Chain"] = "Folgequest Einklappen";
L["Excluded"] = "Zu Filter Ausgeblendet hinzugefügt";
L["Completion"] = "Komplettierung";
L["ID"] = "ID";
L["Reverse Sort"] = "Umgekehrte Sortierung";
L["Earned By"] = "Erzielt durch";
L["Account"] = "Account";
L["Tabs"] = "Tabs";
L["Special Categories"] = "Spezial Kategorie";
L["Current Zone"] = "Aktuelle Zone";
L["Selected Zone"] = "Ausgewählte Zone";
L["View Tutorial"] = "Tutorial anzeigen";
L["Brawler's Guild"] = "Kampfgilde";
L["Buildings"] = "Gebäude";
L["Bur's Mount Collection"] = "Bur's Reittier Collection";
L["Class Hall"] = "Ordenshalle";
L["Covenant Assaults"] = "Paktangriffe";
L["Drops"] = "Beute";
L["Dueler's Guild"] = "Duellantengilde";
L["Faction Assaults"] = "Fraktionsübergriffe";
L["Focused"] = "Zu Fokus Filter hinzugefügt";
L["Gifts"] = "Geschenke";
L["Gladiator's Sanctum"] = "Heiligtum des Gladiators";
L["Glory"] = "Standard";
L["Holidays"] = "Feiertage";
L["Invasions"] = "Invasionen";
L["Legion Assaults"] = "Angriffe der Legion";
L["N'Zoth Assaults"] = "Angriffe von N'Zoth";
L["Necrolords Assault"] = "Necrolord Paktangriff";
L["Other"] = "Andere";
L["Other wings"] = "Weitere Flügel";
L["Pirates' Day"] = "Piratentag";
L["Rated"] = "Gewertet";
L["Recruit-a-Friend"] = "Werbt einen Freund";
L["Shipyard"] = "Werft";
L["Southshore vs. Tarren Mill"] = "Süderstade vs. Tarrens Mühle";
L["Stables"] = "Ställe";
L["Strand of the Ancients"] = "Strand der Uralten";
L["The Entitled"] = "Der/die Titulierte";
L["Vendor"] = "Verkäufer";
L["Zones"] = "Zones";
L["Realm First!"] = "Realm First!";
L["Leveling"] = "Level";
L["Level 80"] = "Level 80";
L["Level 85"] = "Level 85";
L["Level 90"] = "Level 90";
L["450 skill"] = "Fertigkeit 450";
L["525 skill"] = "Fertigkeit 525";
L["600 skill"] = "Fertigkeit 600";
L["BlizzCon"] = "BlizzCon";
L["Collector's Edition"] = "Collector's Edition";
L["Diablo III"] = "Diablo III";
L["Overwatch"] = "Overwatch";
L["StarCraft II"] = "StarCraft II";
L["Hearthstone"] = "Hearthstone";
L["Heroes of the Storm"] = "Heroes of the Storm";
L["Warcraft III: Reforged"] = "Warcraft III: Reforged";
L["WoW's Anniversary"] = "WoW's Geburtstag";
L["WoW's 18th Anniversary"] = "WoW's 18. Geburtstag";
L["Season"] = "Saison";
L["Feast of Winter Veil"] = "Winterhauch";
L["Noblegarden"] = "Nobelgarten";
L["Children's Week"] = "Kinderwoche";
L["Hallow's End"] = "Schlotternächte";
L["Lunar Festival"] = "Mondfest";
L["Midsummer Fire Festival"] = "Sonnenwende";
L["Brewfest"] = "Braufest";
L["Pirates' Day"] = "Piratentag";
L["Pilgrim's Bounty"] = "Die Pilgerfreuden";
L["Day of the Dead"] = "Tag der Toten";
L["Love is in the Air"] = "Liebe liegt in der Luft";
L["Darkmoon Faire"] = "Dunkelmond-Jahrmarkt";
L["Soulforges"] = "Die Seelenschmieden";
L["Fracture Chambers"] = "Frakturkammern";
L["Skoldus Hall"] = "Skoldushalle";
L["Coldheart Interstitia"] = "Kaltherzinterstitia";
L["Mort'regar"] = "Mort'regar";
L["Upper Reaches"] = "Die Oberen Ebenen";
L["Assault on Azsuna"] = "Schlacht um Azsuna";
L["Assault on Highmountain"] = "Schlacht um den Hochberg";
L["Assault on Stormheim"] = "Schlacht um Sturmheim";
L["Assault on Val'sharah"] = "Schlacht um Val'sharah";
L["Assault on Tiragarde Sound"] = "Angriff Tiragardesund";
L["Assault on Drustvar"] = "Angriff Drustvar";
L["Assault on Stormsong Valley"] = "Angriff Sturmsangtal";
L["Assault on Nazmir"] = "Angriff Nazmir";
L["Assault on Vol'dun"] = "Angriff Vol'dun";
L["Assault on Zuldazar"] = "Angriff Zuldazar";
L["Assault: N'Zoth (Uldum)"] = "Angriffe von N'Zoth (Uldum)";
L["Assault: Amathet"] = "Angriff: Vorstoß der Amathet (Amathet)";
L["Assault: Aqir"] = "Angriff: Ausgegrabene Aqir (Aqir)";
L["Assault: N'Zoth (Vale of Eternal Blossoms)"] = "Angriffe von N'Zoth (Das Tal der ewigen Blüten)";
L["Assault: Mogu"] = "Angriff: Die verfeindeten Klans (Mogu)";
L["Assault: Mantid"] = "Angriff: Der unendliche Schwarm (Mantid)";
L["Necrolord Assault"] = "Necrolord Paktangriff";
L["Venthyr Assault"] = "Venthyr Paktangriff";
L["Kyrian Assault"] = "Kyrian Paktangriff";
L["Night Fae Assault"] = "Night Fae Paktangriff";
L["This achievement is no longer obtainable"] = "Dieser Erfolg kann nicht länger erzielt werden.";
L["Not earned by:"] = "Nicht erzielt durch:";
L["Part of a chain"] = "Teil einer Folgequest";
L["Required for"] = "Wird benötigt für...";
L["Objectives progress"] = "Erfolgs-Fortschritt";
L["Collecting data"] = "Collecting data";
L["Not part of set"] = "Nicht Teil des Transmog-Sets";
L["This achievement can't be earned by this character."] = "Der Erfolg kann nicht von diesem Charakter erzielt werden.";
L["This character's class has no transmog set that meet the requirements."] = "Die Klasse deines Charakters erfüllt nicht die Anforderungen für dieses Transmog-Set.";
L["Wowhead"] = "Wowhead";
L["Go to"] = "Gehe zu";
L["Other locations"] = "Weitere...";
L["Transmog Sets"] = "Transmog-Sets";
L["Xu-Fu's Pet Guides"] = "Xu-Fu's Pet Guides";
L["More"] = "Mehr...";
L["Focus"] = "Fokus";
L["Clear focus"] = "Fokus Filter löschen.";
L["Exclude"] = "Ausblenden";
L["Include"] = "Hinzufügen";
L["No achievements are available with the current set of filters"] = "Es können keine Erfolge mit den von dir gesetzten Filtern angezeigt werden.";

