local _, addon = ...
local L = addon.Localization.NewLocale("esES")
if not L then return end

KrowiAF.PluginsApi:LoadPluginLocalization(L);

-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2026-05-27 12-37-18 ]] --
L["Alchemy"] = "Alquimia"
L["Alterac Valley"] = "Valle de Alterac"
L["Arathi Basin"] = "Cuenca de Arathi"
L["Argent Tournament"] = "Torneo Argenta"
L["Battle"] = "Duelo"
L["Battle for Gilneas"] = "La Batalla por Gilneas"
L["Blacksmithing"] = "Herrería"
L["Collect"] = "Recolección"
L["Collections"] = "Colecciones"
L["Covenant Sanctums"] = "Sagrarios de la curia"
L["Decor Duel"] = "Duelo de adornos"
L["Deephaul Ravine"] = "Barranco de Cargahonda"
L["Deepwind Gorge"] = "Cañón del Céfiro"
L["Delves"] = "Profundidades"
L["Dragon Isle Drake Cosmetics"] = "Cosméticos de draco de las Islas Dragón"
L["Dragon Isles"] = "Islas Dragón"
L["Enchanting"] = "Encantamiento"
L["Engineering"] = "Ingeniería"
L["Exploration"] = "Exploración"
L["Eye of the Storm"] = "Ojo de la Tormenta"
L["Feats of Strength"] = "Proezas de fuerza"
L["Heart of Azeroth"] = "Corazón de Azeroth"
L["Herbalism"] = "Herboristería"
L["Island Expeditions"] = "Expediciones insulares"
L["Isle of Conquest"] = "Isla de la Conquista"
L["Jewelcrafting"] = "Joyería"
L["Leatherworking"] = "Peletería"
L["Midsummer"] = "Solsticio"
L["Mining"] = "Minería"
L["Pet Battles"] = "Duelos de mascotas"
L["Prey"] = "Presa"
L["Promotions"] = "Promociones"
L["Ritual Sites"] = "Lugares de rituales"
L["Seething Shore"] = "Costa Hirviente"
L["Silvershard Mines"] = "Minas Lonjaplata"
L["Skinning"] = "Desuello"
L["Slayer's Rise"] = "Alto del Asesino"
L["Tailoring"] = "Sastrería"
L["Temple of Kotmogu"] = "Templo de Kotmogu"
L["Training Grounds"] = "Campo de Entrenamiento"
L["Twin Peaks"] = "Cumbres Gemelas"
L["Void Assaults"] = "Asaltos del Vacío"
L["War Effort"] = "Esfuerzo de guerra"
L["Warsong Gulch"] = "G. Grito de Guerra"
L["Winter Veil"] = "Festival de Invierno"
L["Wintergrasp"] = "Conquista del Invierno"