local _, addon = ...
local L = addon.Localization.NewLocale("itIT")
if not L then return end

KrowiAF.PluginsApi:LoadPluginLocalization(L);

-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2026-06-28 15-04-56 ]] --
L["Alchemy"] = "Alchimia"
L["Alterac Valley"] = "Valle d'Alterac"
L["Arathi Basin"] = "Bacino d'Arathi"
L["Argent Tournament"] = "Torneo d'Argento"
L["Battle"] = "Scontri"
L["Battle for Gilneas"] = "Battaglia per Gilneas"
L["Blacksmithing"] = "Forgiatura"
L["Collect"] = "Collezione"
L["Collections"] = "Collezioni"
L["Covenant Sanctums"] = "Santuari delle Congreghe"
L["Decor Duel"] = "Duello di Decorazioni"
L["Deephaul Ravine"] = "Gola Cavafonda"
L["Deepwind Gorge"] = "Scavi di Ventotetro"
L["Delves"] = "Scorribande"
L["Dragon Isle Drake Cosmetics"] = "Oggetti cosmetici dei Drachi delle Isole dei Draghi"
L["Dragon Isles"] = "Isole dei Draghi"
L["Enchanting"] = "Incantamento"
L["Engineering"] = "Ingegneria"
L["Exploration"] = "Esplorazione"
L["Eye of the Storm"] = "Occhio del Ciclone"
L["Feats of Strength"] = "Prove di forza"
L["Heart of Azeroth"] = "Cuore di Azeroth"
L["Herbalism"] = "Erbalismo"
L["Island Expeditions"] = "Scorrerie sulle Isole"
L["Isle of Conquest"] = "Isola della Conquista"
L["Jewelcrafting"] = "Oreficeria"
L["Leatherworking"] = "Conciatura"
L["Midsummer"] = "Mezza Estate"
L["Mining"] = "Estrazione"
L["Omnium Folio"] = "Foglio dell'Omnium"
L["Pet Battles"] = "Scontri tra mascotte"
L["Prey"] = "Preda"
L["Promotions"] = "Promozioni"
L["Ritual Sites"] = "Siti Rituali"
L["Seething Shore"] = "Spiaggia Ribollente"
L["Silvershard Mines"] = "Miniere di Cupargento"
L["Skinning"] = "Scuoiatura"
L["Slayer's Rise"] = "Altura del Carnefice"
L["Tailoring"] = "Sartoria"
L["Temple of Kotmogu"] = "Tempio di Kotmogu"
L["Training Grounds"] = "Campi d'Addestramento"
L["Twin Peaks"] = "Picchi Gemelli"
L["Val and Naigtal"] = "Val e Naigtal"
L["Void Assaults"] = "Assalti del Vuoto"
L["War Effort"] = "Sforzo Bellico"
L["Warsong Gulch"] = "Forra dei Cantaguerra"
L["Winter Veil"] = "Grande Inverno"
L["Wintergrasp"] = "Lungoinverno"