local _, addon = ...
local L = addon.Localization.NewLocale("koKR")
if not L then return end

KrowiAF.PluginsApi:LoadPluginLocalization(L);

-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

L["Alchemy"] = "연금술"
L["Alterac Valley"] = "알터랙 계곡"
L["Arathi Basin"] = "아라시 분지"
L["Argent Tournament"] = "은빛십자군 마상시합"
L["Ashran"] = "아쉬란"
L["Battle"] = "대전"
L["Battle for Gilneas"] = "길니아스 전투지"
L["Blacksmithing"] = "대장기술"
L["Collect"] = "수집"
L["Collections"] = "수집품"
L["Covenant Sanctums"] = "성약의 단 성소"
L["Decor Duel"] = "하우징 장식 결투"
L["Deephaul Ravine"] = "깊은광혈 협곡"
L["Deepwind Gorge"] = "깊은바람 협곡"
L["Delves"] = "구렁"
L["Dragon Isle Drake Cosmetics"] = "용의 섬 비룡 꾸미기"
L["Dragon Isles"] = "용의 섬"
L["Enchanting"] = "마법부여"
L["Engineering"] = "기계공학"
L["Exploration"] = "탐험"
L["Eye of the Storm"] = "폭풍의 눈"
L["Feats of Strength"] = "위업"
L["Heart of Azeroth"] = "아제로스의 심장"
L["Herbalism"] = "약초채집"
L["Island Expeditions"] = "군도 탐험"
L["Isle of Conquest"] = "정복의 섬"
L["Jewelcrafting"] = "보석세공"
L["Leatherworking"] = "가죽세공"
L["Midsummer"] = "한여름 축제"
L["Mining"] = "채광"
L["Pet Battles"] = "애완동물 대전"
L["Prey"] = "사냥감"
L["Promotions"] = "이벤트"
L["Remix: Mists of Pandaria"] = "리믹스: 판다리아의 안개"
L["Ritual Sites"] = "의식 지점"
L["Seething Shore"] = "들끓는 해안"
L["Silvershard Mines"] = "은빛수정 광산"
L["Skinning"] = "무두질"
L["Slayer's Rise"] = "학살자의 오름길"
L["Tailoring"] = "재봉술"
L["Temple of Kotmogu"] = "코트모구의 사원"
L["Tol Barad"] = "톨 바라드"
L["Training Grounds"] = "훈련장"
L["Twin Peaks"] = "쌍둥이 봉우리"
L["Void Assaults"] = "공허 공세"
L["War Effort"] = "전쟁 지원"
L["Warsong Gulch"] = "전쟁노래 협곡"
L["Winter Veil"] = "겨울맞이 축제"
L["Wintergrasp"] = "겨울손아귀"
