local addonName, addon = ...;
local L = LibStub(addon.Libs.AceLocale):NewLocale(addonName, "ptBR");
if not L then return end
addon.L = L;

KrowiAF.PluginsApi:LoadPluginLocalization(L);

-- [[ https://legacy.curseforge.com/wow/addons/krowi-achievement-filter/localization ]] --
-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2025-06-18 15-02-50 ]] --
L["%c"] = true
L["%d/%m/%Y %I:%M %p"] = true
L["%m/%d/%Y %I:%M %p"] = true
L["%m/%d/%Y %R"] = true
L["%Y/%m/%d %I:%M %p"] = true
L["%Y/%m/%d %R"] = true
L["10th Anniversary"] = "10º Aniversário"
L["450 skill"] = "450 de habilidade"
L["525 skill"] = "525 de habilidade"
L["600 skill"] = "600 de habilidade"
L["Academy Ascent"] = "Ascensão da Academia"
L["Account"] = "Conta"
L["Account wide (default)"] = "Na conta (padrão)"
L["Achievement browsing history"] = "Histórico de navegação das Conquistas"
L["Achievement Calendar"] = "Calendário de Conquistas"
L["Achievement is Completed"] = "Conquista concluída"
L["Achievement is Completed Desc"] = "Mostre o Critério da Conquista mesmo se a Conquista já estiver completa."
L["Achievement is excluded"] = "Esta conquista está excluída"
L["Achievement is watched"] = "Esta conquista está na sua {watchList}."
L["Achievement points earned by"] = "Pontos de Conquista ganhados por"
L["Achievement shown temporarily"] = "Esta conquista está sendo exibida temporariamente porque não corresponde a nenhum dos filtros definidos"
L["Achievement was Not Earned by Me"] = "Conquista não foi obtida por mim"
L["Achievement was Not Earned by Me Desc"] = "Mostrar os Critérios da Conquista se ela ainda não foi obtida pelo personagem atual. Isso permite maior controle se você joga com vários personagens."
L["Achievement Window"] = "Aba de Conquistas"
L["Achievement window height offset Desc"] = "A altura que será adicionada ou removida da altura padrão da janela de conquistas. Esse valor pode ser ajustado enquanto a janela de conquistas estiver aberta e uma das abas adicionadas pelo {addonName} estiver selecionada. Isso pode ter um impacto (1) no jogo. (1) Quedas de FPS e travamentos podem ocorrer ao ajustar o valor, mas NÃO durante o uso normal do addon"
L["Achievements"] = "Conquistas"
L["Achievements width offset Desc"] = "\"A largura que será adicionada à largura padrão da janela de conquistas. Esse valor pode ser ajustado enquanto a janela de conquistas estiver aberta e uma das abas adicionadas pelo {addonName} estiver selecionada. Isso pode ter um impacto (1) no jogo. (1) Podem ocorrer quedas de FPS e travamentos ao ajustar o valor, mas NÃO durante o uso normal do addon"
L["Active"] = "Ativo"
L["Active events"] = "eventos ativos"
L["Active Events"] = "Eventos Ativos"
L["Add addon name to world map icon"] = "Adicionar nome do addon ao ícone do mapa-múndi"
L["Added in version"] = "Adicionado na versão"
L["Adjustable Categories"] = "Categorias Ajustáveis"
L["Aki the Chosen"] = "Aki, a Escolhida"
L["Allied Race"] = "Raça Aliada"
L["Alt"] = true
L["Always show realm"] = "Sempre mostre o reino"
L["Amathet"] = "Amatet"
L["Andurs"] = true
L["Apex Canopy River Run"] = "Disputa do Rio do Dossel do Ápice"
L["Aqir"] = true
L["Archive Ambit"] = "Âmbito do Arquivo"
L["Are you sure you want to delete character?"] = "Tem certeza que deseja apagar este personagem?"
L["Assault on Azsuna"] = "Ataque a Azsuna"
L["Assault on Drustvar"] = "Ataque a Drustvar"
L["Assault on Highmountain"] = "Ataque a Alta Montanha"
L["Assault on Nazmir"] = "Ataque a Nazmir"
L["Assault on Stormheim"] = "Ataque a Trommheim"
L["Assault on Stormsong Valley"] = "Ataque ao Vale Trovamare"
L["Assault on Tiragarde Sound"] = "Ataque ao Estreito Tiragarde"
L["Assault on Val'sharah"] = "Ataque a Val'sharah"
L["Assault on Vol'dun"] = "Ataque a Vol'dun"
L["Assault on Zuldazar"] = "Ataque a Zuldazar"
L["Assault: Amathet"] = "Ataque: Amatet"
L["Assault: Aqir"] = "Ataque: Aqir"
L["Assault: Mantid"] = "Ataque: Mantídeos"
L["Assault: Mogu"] = "Ataque: Mogu"
L["Assault: N'Zoth (Uldum)"] = "Ataque: N'Zoth (Uldum)"
L["Assault: N'Zoth (Vale of Eternal Blossoms)"] = "Ataque: N'Zoth (Vale das Flores Eternas)"
L["Author"] = "Autor"
L["Azerothian Archives"] = "Arquivo Azerothiano"
L["Azsuna"] = true
L["Azure Span"] = "Vasta Lazúli"
L["Blizzard"] = true
L["BlizzCon"] = true
L["Brackenhide Hollow"] = "Clareira de Courambaia"
L["Brawler's Guild"] = "Guilda dos Brigões"
L["Breaknecking Races"] = "Corridas de Pé-na-Tábua"
L["Brewfest"] = "CervaFest"
L["Broken Isles Cup"] = "Copa das Ilhas Partidas"
L["Buildings"] = "Construções"
L["Burning Pandaren Spirit"] = "Espírito Pandaren Flamejante"
L["Button"] = "Botão"
L["Calendar"] = "Calendário"
L["Calendar button"] = "Botão do Calendário"
L["Calendar Events"] = "Calendário de Eventos"
L["Categories"] = "Categorias"
L["Chains of Domination"] = "Correntes da Dominação"
L["Characters"] = "Personagens"
L["Chat messages"] = "Mensagens no chat"
L["Checked"] = "Verificado"
L["Children's Week"] = "Semana das Crianças"
L["Clear all"] = "Limpar tudo"
L["Click here to view in achievement window"] = "Clique aqui para ver na janela de conquistas"
L["Click here to view in achievements"] = "Clique aqui para ver nas conquistas"
L["Cliffside Circuit"] = "Circuito do Penhasco"
L["Cobalt Assembly"] = "Junção Cobáltica"
L["Coldheart Interstitia"] = "Interstício Frigicordis"
L["Collecting data"] = "Coletando dados"
L["Collector's Edition"] = "Edição de Colecionador"
L["Comments"] = "Comentários"
L["Community Feast"] = "Banquete da Comunidade"
L["Community Feast: Active"] = "Banquete da Comunidade: Ativo"
L["Covenant"] = "Pacto"
L["Covenant assaults"] = "ataques do Pacto"
L["Covenant Assaults"] = "Ataques do Pacto"
L["Credits"] = "Créditos"
L["Criteria"] = "Critério"
L["Criteria is Completed"] = "Critério está completo"
L["Ctrl"] = true
L["CurseForge"] = true
L["Dark Heart"] = "Coração Sombrio"
L["Darkmoon Faire"] = "Feira de Negraluna"
L["Dastardly Duos"] = "Duplas da Discórdia"
L["Day of the Dead"] = "Dia dos Mortos"
L["Debug"] = true
L["Defending Azeroth Assaults"] = "Defendendo Ataques a Azeroth"
L["Defending the Ruby Sanctum"] = "Defendendo o Santuário Rubi"
L["Diablo"] = true
L["Diablo III"] = true
L["Diablo IV"] = true
L["Discord"] = true
L["Donations"] = "Doações"
L["Dos-Ryga"] = true
L["Dragonbane Keep"] = "Bastilha de Ruína Dragônica"
L["Dragonblight"] = "Ermo das Serpes"
L["Dragonflight (pre-patch)"] = true
L["Dreamsurge"] = "Surto Onírico"
L["Drustvar"] = true
L["Dueler's Guild"] = "Guilda dos Duelistas"
L["during"] = "durante"
L["Dustwallow Marsh"] = "Pântano Vadeoso"
L["Earned By"] = "Obtido por"
L["Eastern Kingdoms Cup"] = "Copa dos Reinos do Leste"
L["Echoes of Doom"] = "Ecos da Ruína"