local addonName, addon = ...;
local L = LibStub(addon.Libs.AceLocale):NewLocale(addonName, "ruRU");
if not L then return end

-- [[ https://legacy.curseforge.com/wow/addons/krowi-achievement-filter/localization ]] --
-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2024-01-21 12-59-36 ]] --
L["AchievementsTabFixes"] = "Вкладки Достижений исправлены"
L["AchievementsTabFixes Desc"] = "Данный плагин позволяет исправить Вкладки Достижений, описанные ниже."
L["Add To Right Click Menu"] = "Добавить в меню по правому щелчку"
L["Add To Right Click Menu Desc"] = "Добавить настройку в меню по правому щелчку оно направить вас на тактику если в {iat} есть такая информация."
L["Alert System Overwrite Desc"] = "Настройки местоположения не активны, когда {addon} включен. Перемещение рамок добычи/предупреждений приведет к тому же результату."
L["At least version is required"] = "Необходима версия '{version}'"
L["Better Wardrobe"] = "Лучший гардероб"
L["Better Wardrobe Desc"] = "Этот плагин исправляет ссылку на гардероб, сломанную {betterWardrobe}. Без альтернатив."
L["ElvUI"] = true
L["ElvUI Desc"] = "Каждая из приведенных ниже настроек контролируется ElvUI и носит исключительно информационный характер. Чтобы изменить их, перейдите в меню игры -> ElvUI -> Скины и отметьте нужные опции. Смотрите каждую опцию ниже, чтобы узнать, что нужно проверить."
L["ElvUI Fix World Map Button"] = "Исправление кнопки у карты мира"
L["ElvUI Fix World Map Button Desc"] = "Когда настройка ElvUI Maps -> World Map -> Smaller World Map включена, это исправление необходимо"
L["ElvUI Remove Parchment"] = "Убрать задний пергамент"
L["ElvUI Remove Parchment Desc"] = "Убрать задний пергамент из Календарных дней ->Убрать пергамент"
L["ElvUI Skin Ace3"] = "Skin Ace3"
L["ElvUI Skin Ace3 Desc"] = "Применить шкурку ElvUI к Options. -> Ace3"
L["ElvUI Skin Achievements"] = "Шкурка Достижений"
L["ElvUI Skin Achievements Desc"] = "Применить шкурку ElvUI к  окну достижений -> Blizzard + Achievements"
L["ElvUI Skin Alert Frames"] = "Шкурка окна предупреждений"
L["ElvUI Skin Alert Frames Desc"] = "Применить шкурку ElvUI к окну предупреждений Alert Frames. -> Blizzard + Alert Frames"
L["ElvUI Skin Calendar"] = "Шкурка Календаря"
L["ElvUI Skin Calendar Desc"] = "Применить шкурку ElvUI к Календарю Calendar. -> Blizzard + Calendar Frame"
L["ElvUI Skin Data Manager"] = "Шкурка Менеджера данных"
L["ElvUI Skin Data Manager Desc"] = "Применить шкурку ElvUI к Менеджеру данных Data Manager Window. -> Blizzard + Achievements"
L["ElvUI Skin Misc Frames"] = "Шкурка Остальных окон"
L["ElvUI Skin Misc Frames Desc"] = "Применить шкурку ElvUI к меню фильтров, меню по правому клику и всплывающим окнам"
L["ElvUI Skin Tooltip"] = "Шкурка Подсказки"
L["ElvUI Skin Tooltip Desc"] = "Применить шкурку ElvUI к Подсказкам"
L["ElvUI Skin Tutorials"] = "Шкурка Обучения"
L["ElvUI Skin Tutorials Desc"] = "Применить шкурку ElvUI к Обучению"
L["GW2_UI"] = "GW 2 UI"
L["GW2_UI Modules Desc"] = "Для изменения, зайдите в Game Menu -> GW 2 UI -> General -> Modules и выберите нужные настройки. Смотрите нужные настройки которые вам нужны."
L["GW2_UI Skin Achievements"] = "Шкурка Достижений"
L["GW2_UI Skin Achievements Desc"] = "Применить GW 2 UI для окна Достижений -> Достижения"
L["GW2_UI Skin Alert Frames"] = "Шкурка для окна оповещений"
L["GW2_UI Skin Alert Frames Desc"] = "Применить шкурку GW 2 UI для Окон оповещения."
L["GW2_UI Skin DropDown"] = "Шкурка выпадающая"
L["GW2_UI Skin DropDown Desc"] = "Применить шкурку Drop-Down для меню фильтров и меню по Правому щелчку."
L["GW2_UI Skin Popup Notifications"] = "Шкурка для всплывающий оповещений"
L["GW2_UI Skin Popup Notifications Desc"] = "Применить шкурку GW 2 UI  для всплывающих диалогов."
L["GW2_UI Skin Tooltip"] = "Шкурка Подсказок"
L["GW2_UI Skin Tooltip Desc"] = "Применить шкурку GW 2 UI  для подсказок."
L["GW2_UI Skins Desc"] = "Каждая настройки ниже контролируется GW 2 UI  и содержит информацию. Для её изменения пройдите Главное меню -> GW 2 UI ->Главная -> Шкурки и выберите нужные. Смотрите нужные настройки какие вам нужно выбрать."
L["IAT Tactics"] = "IAT Тактики"
L["Instance Achievement Tracker"] = true
L["Instance Achievement Tracker Desc"] = "Этот плагин позволяет добавить экстра меню по Правому Клику предмет для {iat}."
L["Instance Achievement Tracker PluginText"] = "|T:1:8|t- Ярлычек для {plugin_iat} если тактика для достижения доступна ({plugin_iat}  и  {plugin_enabled})."
L["RenameExplorationDragonIslesCategory"] = "Переименовать Исследование -> Драконьи острова в Dragonflight"
L["RenameExplorationDragonIslesCategory Desc"] = "Переименовывать Исследование -> Драконьи острова в Dragonflight"
L["Unsupported GW2_UI Desc"] = "Текущая версия '{version}' GW 2 UI не поддерживаешь."
L["Zygor Guides Viewer"] = "Просмотр гайдов от Зигора"
L["Zygor Guides Viewer Desc"] = "Этот плагин добавляет увеличительное стекло во вкладки достижей. Без настроек."