local _, addon = ...;
if not addon.Util.IsClassicWithAchievements then
    return;
end
local L = addon.Localization.NewLocale("ruRU", true)
if not L then return end

-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2026-05-27 12-34-29 ]] --
L["Completed"] = "Заработано"
L["EJ_GetInstanceInfo230"] = "Забытый город"
L["EJ_GetInstanceInfo246"] = "Некроситет"
L["EJ_GetInstanceInfo247"] = "Аукенайские гробницы"
L["EJ_GetInstanceInfo248"] = "Бастионы Адского Пламени"
L["EJ_GetInstanceInfo249"] = "Терраса Магистров"
L["EJ_GetInstanceInfo250"] = "Гробницы маны"
L["EJ_GetInstanceInfo251"] = "Старые предгорья Хилсбрада"
L["EJ_GetInstanceInfo252"] = "Сетеккские залы"
L["EJ_GetInstanceInfo253"] = "Темный лабиринт"
L["EJ_GetInstanceInfo254"] = "Аркатрац"
L["EJ_GetInstanceInfo255"] = "Черные топи"
L["EJ_GetInstanceInfo256"] = "Кузня Крови"
L["EJ_GetInstanceInfo257"] = "Ботаника"
L["EJ_GetInstanceInfo258"] = "Механар"
L["EJ_GetInstanceInfo259"] = "Разрушенные залы"
L["EJ_GetInstanceInfo260"] = "Узилище"
L["EJ_GetInstanceInfo261"] = "Паровое подземелье"
L["EJ_GetInstanceInfo262"] = "Нижетопь"
L["EJ_GetInstanceInfo271"] = "Ан'кахет: Старое Королевство"
L["EJ_GetInstanceInfo272"] = "Азжол-Неруб"
L["EJ_GetInstanceInfo273"] = "Крепость Драк'Тарон"
L["EJ_GetInstanceInfo274"] = "Гундрак"
L["EJ_GetInstanceInfo275"] = "Чертоги Молний"
L["EJ_GetInstanceInfo276"] = "Залы Отражений"
L["EJ_GetInstanceInfo277"] = "Чертоги Камня"
L["EJ_GetInstanceInfo278"] = "Яма Сарона"
L["EJ_GetInstanceInfo279"] = "Очищение Стратхольма"
L["EJ_GetInstanceInfo280"] = "Кузня Душ"
L["EJ_GetInstanceInfo281"] = "Нексус"
L["EJ_GetInstanceInfo282"] = "Окулус"
L["EJ_GetInstanceInfo283"] = "Аметистовая крепость"
L["EJ_GetInstanceInfo284"] = "Испытание чемпиона"
L["EJ_GetInstanceInfo285"] = "Крепость Утгард"
L["EJ_GetInstanceInfo286"] = "Вершина Утгард"
L["EJ_GetInstanceInfo311"] = "Залы Алого ордена"
L["EJ_GetInstanceInfo316"] = "Монастырь Алого ордена"
L["EJ_GetInstanceInfo559"] = "Верхняя часть пика Черной горы"
L["EJ_GetInstanceInfo63"] = "Мёртвые копи"
L["EJ_GetInstanceInfo64"] = "Крепость Темного Клыка"
L["EJ_GetInstanceInfo741"] = "Огненные Недра"
L["EJ_GetInstanceInfo742"] = "Логово Крыла тьмы"
L["EJ_GetInstanceInfo743"] = "Руины Ан'Киража"
L["EJ_GetInstanceInfo744"] = "Ан'Кираж"
L["EJ_GetInstanceInfo745"] = "Каражан"
L["EJ_GetInstanceInfo746"] = "Логово Груула"
L["EJ_GetInstanceInfo747"] = "Логово Магтеридона"
L["EJ_GetInstanceInfo748"] = "Змеиное святилище"
L["EJ_GetInstanceInfo749"] = "Крепость Бурь"
L["EJ_GetInstanceInfo750"] = "Битва за гору Хиджал"
L["EJ_GetInstanceInfo751"] = "Черный Храм"
L["EJ_GetInstanceInfo752"] = "Плато Солнечного Колодца"
L["EJ_GetInstanceInfo753"] = "Хранилище Аркавона"
L["EJ_GetInstanceInfo754"] = "Наксрамас"
L["EJ_GetInstanceInfo755"] = "Обсидиановое святилище"
L["EJ_GetInstanceInfo756"] = "Око Вечности"
L["EJ_GetInstanceInfo757"] = "Испытание крестоносца"
L["EJ_GetInstanceInfo758"] = "Цитадель Ледяной Короны"
L["EJ_GetInstanceInfo759"] = "Ульдуар"
L["EJ_GetInstanceInfo76"] = "Зул'Гуруб"
L["EJ_GetInstanceInfo760"] = "Логово Ониксии"
L["EJ_GetInstanceInfo761"] = "Рубиновое Святилище"
L["EJ_GetInstanceInfo77"] = "Зул'Аман"
L["Not Completed"] = "Не завершено"