local _, addon = ...;
if not addon.Util.IsClassicWithAchievements then
    return;
end
local L = addon.Localization.NewLocale("zhCN", true)
if not L then return end

-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2026-05-27 12-34-30 ]] --
L["Completed"] = "已获得"
L["EJ_GetInstanceInfo230"] = "厄运之槌"
L["EJ_GetInstanceInfo246"] = "通灵学院"
L["EJ_GetInstanceInfo247"] = "奥金尼地穴"
L["EJ_GetInstanceInfo248"] = "地狱火城墙"
L["EJ_GetInstanceInfo249"] = "魔导师平台"
L["EJ_GetInstanceInfo250"] = "法力陵墓"
L["EJ_GetInstanceInfo251"] = "旧希尔斯布莱德丘陵"
L["EJ_GetInstanceInfo252"] = "赛泰克大厅"
L["EJ_GetInstanceInfo253"] = "暗影迷宮"
L["EJ_GetInstanceInfo254"] = "禁魔监狱"
L["EJ_GetInstanceInfo255"] = "黑色沼泽"
L["EJ_GetInstanceInfo256"] = "鲜血熔炉"
L["EJ_GetInstanceInfo257"] = "生态船"
L["EJ_GetInstanceInfo258"] = "能源舰"
L["EJ_GetInstanceInfo259"] = "破碎大厅"
L["EJ_GetInstanceInfo260"] = "奴隶围栏"
L["EJ_GetInstanceInfo261"] = "蒸汽地窟"
L["EJ_GetInstanceInfo262"] = "幽暗沼泽"
L["EJ_GetInstanceInfo271"] = "安卡赫特：古代王国"
L["EJ_GetInstanceInfo272"] = "艾卓-尼鲁布王国"
L["EJ_GetInstanceInfo273"] = "达克萨隆要塞"
L["EJ_GetInstanceInfo274"] = "古达克"
L["EJ_GetInstanceInfo275"] = "闪电大厅"
L["EJ_GetInstanceInfo276"] = "映像大厅"
L["EJ_GetInstanceInfo277"] = "岩石大厅"
L["EJ_GetInstanceInfo278"] = "萨隆矿坑"
L["EJ_GetInstanceInfo279"] = "净化斯坦索姆"
L["EJ_GetInstanceInfo280"] = "灵魂洪炉"
L["EJ_GetInstanceInfo281"] = "魔枢"
L["EJ_GetInstanceInfo282"] = "魔环"
L["EJ_GetInstanceInfo283"] = "紫罗兰监狱"
L["EJ_GetInstanceInfo284"] = "冠军的试炼"
L["EJ_GetInstanceInfo285"] = "乌特加德城堡"
L["EJ_GetInstanceInfo286"] = "乌特加德之巅"
L["EJ_GetInstanceInfo311"] = "血色大厅"
L["EJ_GetInstanceInfo316"] = "血色修道院"
L["EJ_GetInstanceInfo559"] = "黑石塔上层"
L["EJ_GetInstanceInfo63"] = "死亡矿井"
L["EJ_GetInstanceInfo64"] = "影牙城堡"
L["EJ_GetInstanceInfo741"] = "熔火之心"
L["EJ_GetInstanceInfo742"] = "黑翼之巢"
L["EJ_GetInstanceInfo743"] = "安其拉废墟"
L["EJ_GetInstanceInfo744"] = "安其拉神殿"
L["EJ_GetInstanceInfo745"] = "卡拉赞"
L["EJ_GetInstanceInfo746"] = "格鲁尔的巢穴"
L["EJ_GetInstanceInfo747"] = "玛瑟里顿的巢穴"
L["EJ_GetInstanceInfo748"] = "毒蛇神殿"
L["EJ_GetInstanceInfo749"] = "风暴要塞"
L["EJ_GetInstanceInfo750"] = "海加尔山之战"
L["EJ_GetInstanceInfo751"] = "黑暗神殿"
L["EJ_GetInstanceInfo752"] = "太阳之井高地"
L["EJ_GetInstanceInfo753"] = "阿尔卡冯的宝库"
L["EJ_GetInstanceInfo754"] = "纳克萨玛斯"
L["EJ_GetInstanceInfo755"] = "黑曜石圣殿"
L["EJ_GetInstanceInfo756"] = "永恒之眼"
L["EJ_GetInstanceInfo757"] = "十字军的试炼"
L["EJ_GetInstanceInfo758"] = "冰冠堡垒"
L["EJ_GetInstanceInfo759"] = "奥杜尔"
L["EJ_GetInstanceInfo76"] = "祖尔格拉布"
L["EJ_GetInstanceInfo760"] = "奥妮克希亚的巢穴"
L["EJ_GetInstanceInfo761"] = "红玉圣殿"
L["EJ_GetInstanceInfo77"] = "祖阿曼"
L["Not Completed"] = "未获得"