local _, addon = ...;
if not addon.Util.IsClassicWithAchievements then
    return;
end
local L = addon.Localization.NewLocale("zhTW", true)
if not L then return end

-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2026-05-26 20-54-38 ]] --
L["Completed"] = "已獲得"
L["EJ_GetInstanceInfo230"] = "厄運之槌"
L["EJ_GetInstanceInfo246"] = "通靈學院"
L["EJ_GetInstanceInfo247"] = "奧奇奈地穴"
L["EJ_GetInstanceInfo248"] = "地獄火壁壘"
L["EJ_GetInstanceInfo249"] = "博學者殿堂"
L["EJ_GetInstanceInfo250"] = "法力墓地"
L["EJ_GetInstanceInfo251"] = "逃離敦霍爾德"
L["EJ_GetInstanceInfo252"] = "塞司克大廳"
L["EJ_GetInstanceInfo253"] = "暗影迷宮"
L["EJ_GetInstanceInfo254"] = "禁魔監獄"
L["EJ_GetInstanceInfo255"] = "毒蛇沼澤"
L["EJ_GetInstanceInfo256"] = "血熔爐"
L["EJ_GetInstanceInfo257"] = "波坦尼卡"
L["EJ_GetInstanceInfo258"] = "風暴要塞"
L["EJ_GetInstanceInfo259"] = "破碎大廳"
L["EJ_GetInstanceInfo260"] = "奴隸監獄"
L["EJ_GetInstanceInfo261"] = "蒸汽洞窟"
L["EJ_GetInstanceInfo262"] = "毒沼"
L["EJ_GetInstanceInfo271"] = "安卡罕特：古王國"
L["EJ_GetInstanceInfo272"] = "阿薩－奈幽卜"
L["EJ_GetInstanceInfo273"] = "達薩羅納堡壘"
L["EJ_GetInstanceInfo274"] = "剛卓拉克"
L["EJ_GetInstanceInfo275"] = "閃電大廳"
L["EJ_GetInstanceInfo276"] = "映像大廳"
L["EJ_GetInstanceInfo277"] = "岩石大廳"
L["EJ_GetInstanceInfo278"] = "薩龍礦坑"
L["EJ_GetInstanceInfo279"] = "淨化斯坦索姆"
L["EJ_GetInstanceInfo280"] = "熔爐之魂"
L["EJ_GetInstanceInfo281"] = "奧核之心"
L["EJ_GetInstanceInfo282"] = "奧核之環"
L["EJ_GetInstanceInfo283"] = "紫羅蘭堡"
L["EJ_GetInstanceInfo284"] = "十字軍試煉"
L["EJ_GetInstanceInfo285"] = "俄特加德要塞"
L["EJ_GetInstanceInfo286"] = "俄特加德之巔"
L["EJ_GetInstanceInfo311"] = "血色大廳"
L["EJ_GetInstanceInfo316"] = "血色修道院"
L["EJ_GetInstanceInfo559"] = "黑石塔上層"
L["EJ_GetInstanceInfo63"] = "死亡礦坑"
L["EJ_GetInstanceInfo64"] = "影牙城堡"
L["EJ_GetInstanceInfo741"] = "熔火之心"
L["EJ_GetInstanceInfo742"] = "黑翼之巢"
L["EJ_GetInstanceInfo743"] = "安其拉廢墟"
L["EJ_GetInstanceInfo744"] = "安其拉神廟"
L["EJ_GetInstanceInfo745"] = "卡拉贊"
L["EJ_GetInstanceInfo746"] = "戈魯爾之巢"
L["EJ_GetInstanceInfo747"] = "瑪瑟里頓之巢"
L["EJ_GetInstanceInfo748"] = "毒蛇神殿洞穴"
L["EJ_GetInstanceInfo749"] = "風暴要塞"
L["EJ_GetInstanceInfo750"] = "海加爾山之戰"
L["EJ_GetInstanceInfo751"] = "黑暗神廟"
L["EJ_GetInstanceInfo752"] = "太陽之井高地"
L["EJ_GetInstanceInfo753"] = "亞夏梵穹殿"
L["EJ_GetInstanceInfo754"] = "納克薩瑪斯"
L["EJ_GetInstanceInfo755"] = "黑曜聖所"
L["EJ_GetInstanceInfo756"] = "永恆之眼"
L["EJ_GetInstanceInfo757"] = "十字軍試煉"
L["EJ_GetInstanceInfo758"] = "冰冠城塞"
L["EJ_GetInstanceInfo759"] = "奧杜亞"
L["EJ_GetInstanceInfo76"] = "祖爾格拉布"
L["EJ_GetInstanceInfo760"] = "奧妮克希亞的巢穴"
L["EJ_GetInstanceInfo761"] = "紅玉聖殿"
L["EJ_GetInstanceInfo77"] = "祖阿曼"
L["Not Completed"] = "未獲得"
