local _, addon = ...

local expansion = KrowiAF.NewBuildVersion("Cataclysm", 4)
local minor = expansion:Minor(0)
minor:Patch(1, addon.L["Cataclysm (pre-patch)"])
minor:Patch(3, addon.L["Cataclysm (pre-patch)"])
minor:Patch(6, addon.L["Cataclysm"])
minor = expansion:Minor(1)
minor:Patch(0, addon.L["Rise of the Zandalari"])
minor = expansion:Minor(2)
minor:Patch(0, addon.L["Rage of the Firelands"])
minor:Patch(2, addon.L["Rage of the Firelands"])
minor = expansion:Minor(3)
minor:Patch(0, addon.L["Hour of Twilight"])
minor:Patch(2, addon.L["Hour of Twilight"])
minor = expansion:Minor(4)
minor:Patch(0, addon.L["Cataclysm"])
minor:Patch(1, addon.L["Rage of the Firelands"])
expansion:Register()