-- -- [[ Namespaces ]] --
-- local _, addon = ...;
-- local unitTests = addon.UnitTests;

-- if not unitTests.Active then return; end

-- local filters = addon.Filters;
-- local registerTests = unitTests:RegisterGroup("Filters");

-- registerTests("CompareId a < b", function()
--     WoWUnit.AreEqual(true, filters.CompareIdFunc({ID = 5}, {ID = 10}, false));
-- end);
-- registerTests("CompareId a > b", function()
--     WoWUnit.AreEqual(false, filters.CompareIdFunc({ID = 10}, {ID = 5}, false));
-- end);
-- registerTests("CompareId a < b reverse", function()
--     WoWUnit.AreEqual(false, filters.CompareIdFunc({ID = 5}, {ID = 10}, true));
-- end);
-- registerTests("CompareId a > b reverse", function()
--     WoWUnit.AreEqual(true, filters.CompareIdFunc({ID = 10}, {ID = 5}, true));
-- end);

-- -- 11395 = Diablo's 20th Anniversary, 6 = Level 10
-- local defaultOrder = {};
-- local a, b, c = {ID = 6}, {ID = 11395}, {ID = 7};
-- defaultOrder[a] = 1;
-- defaultOrder[c] = 2;
-- defaultOrder[b] = 3;
-- registerTests("CompareCompletion a < b", function()
--     WoWUnit.AreEqual(true, filters.CompareCompletionFunc(a, b, false, defaultOrder));
-- end);
-- registerTests("CompareCompletion a > b", function()
--     WoWUnit.AreEqual(false, filters.CompareCompletionFunc(b, a, false, defaultOrder));
-- end);
-- registerTests("CompareCompletion a < b reverse", function()
--     WoWUnit.AreEqual(false, filters.CompareCompletionFunc(a, b, true, defaultOrder));
-- end);
-- registerTests("CompareCompletion a > b reverse", function()
--     WoWUnit.AreEqual(true, filters.CompareCompletionFunc(b, a, true, defaultOrder));
-- end);
-- registerTests("CompareCompletion a = b", function()
--     WoWUnit.AreEqual(true, filters.CompareCompletionFunc(a, c, false, defaultOrder));
-- end);
-- registerTests("CompareCompletion a = b reverse", function()
--     WoWUnit.AreEqual(false, filters.CompareCompletionFunc(a, c, true, defaultOrder));
-- end);