local _, addon = ...

local expansion = KrowiAF.NewBuildVersion("MistsOfPandaria", 5)
local minor = expansion:Minor(0)
minor:Patch(4, addon.L["Mists of Pandaria (pre-patch)"])
minor = expansion:Minor(1)
minor:Patch(0, addon.L["Landfall"])
minor = expansion:Minor(2)
minor:Patch(0, addon.L["The Thunder King"])
minor = expansion:Minor(3)
minor:Patch(0, addon.L["Escalation"])
minor = expansion:Minor(4)
minor:Patch(0, addon.L["Siege of Orgrimmar"])
minor:Patch(1, addon.L["Siege of Orgrimmar"])
minor:Patch(2, addon.L["Siege of Orgrimmar"])
expansion:Register()