local _, addon = ...

local expansion = KrowiAF.NewBuildVersion("Dragonflight", 10)
local minor = expansion:Minor(0)
minor:Patch(0, addon.L["Dragonflight (pre-patch)"])
minor:Patch(2, addon.L["Dragonflight"])
minor:Patch(5, addon.L["Trading Post"])
minor:Patch(7, addon.L["Return to the Forbidden Reach"])
minor = expansion:Minor(1)
minor:Patch(0, addon.L["Embers of Neltharion"])
minor:Patch(5, addon.L["Fractures in Time"])
minor:Patch(7, addon.L["Fury Incarnate"])
minor = expansion:Minor(2)
minor:Patch(0, addon.L["Guardians of the Dream"])
minor:Patch(5, addon.L["Seeds of Renewal"])
minor:Patch(6, addon.L["Plunderstorm"])
minor:Patch(7, addon.L["Dark Heart"])